-- 1. Dimensions Exploration: Customers & Products

--Explore Customer Countries
SELECT
  DISTINCT country
FROM
  dim_customers
;

--Explore Product Categories & Hierarchy
SELECT
  DISTINCT category, 
  subcategory,
  product_name
FROM
  dim_products
ORDER BY
  category, subcategory
;


-- 2. Date & Time Exploration

-- Find the date of the first and last order?
-- How many years of sales are available?
SELECT
  MIN(order_date) AS first_order_date,
  MAX(order_date) AS last_order_date,
  DATE_PART('year', AGE(MAX(order_date), MIN(order_date))) AS order_range_years
FROM 
  fact_sales
;

--Find the youngest and oldest customer
SELECT
  MIN(birthdate) AS oldest_birthdate,
  DATE_PART('year', AGE(NOW(), MIN(birthdate))) AS oldest_age,
  MAX(birthdate) AS youngest_birthdate,
  DATE_PART('year', AGE(NOW(), MAX(birthdate))) AS youngest_age
FROM
  dim_customers
;


-- 3. Measures Exploration (Key Business Metrics)

--Find the Total Sales
SELECT SUM(sales_amount) AS total_sales FROM fact_sales; 
--output: 29356250

--Find how many items are sold
SELECT SUM(quantity) AS total_quantity FROM fact_sales; 
--output: 60423

--Find the average selling price
SELECT AVG(price) AS avg_price FROM fact_sales; 
--output: 486.04

--Find the Total number of Orders
SELECT COUNT(order_number) AS total_orders FROM fact_sales; 
--output: 60398

SELECT COUNT(DISTINCT order_number) AS total_orders FROM fact_sales; 
--output: 27659

--Find the Total number of Products
SELECT COUNT(product_name) AS total_products FROM dim_products; 
--output: 295

SELECT COUNT(DISTINCT product_name) AS total_products FROM dim_products; 
--output: 295

--Find the Total number of Customers
SELECT COUNT(customer_key) AS total_customers FROM dim_customers; 
--output: 18484 

SELECT COUNT(DISTINCT customer_key) AS total_customers FROM dim_customers;
--output: 18484 

--Find the Total number of Customers that has placed an order
SELECT COUNT(customer_key) AS total_customers FROM fact_sales; 
--output: 60398

SELECT COUNT(DISTINCT customer_key) AS total_customers FROM fact_sales; 
--output: 18484

-- A consolidated KPI query was also created using UNION ALL to produce a single metrics report, suitable for dashboards and executive summaries.
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(quantity) FROM fact_sales
UNION ALL
SELECT 'Average Price', ROUND(AVG(price), 2) FROM fact_sales
UNION ALL
SELECT 'Total No. Orders', COUNT(DISTINCT order_number) FROM fact_sales
UNION ALL
SELECT 'Total No. Products', COUNT(DISTINCT product_name) FROM dim_products
UNION ALL
SELECT 'Total No. Customers', COUNT(DISTINCT customer_key) FROM dim_customers
;


-- 4. Magnitude Analysis (Category-Level Comparisons)

-- Find total customers by countries
SELECT
  country,
  COUNT(customer_key) AS total_customers
FROM
  dim_customers
GROUP BY
  country
ORDER BY
  total_customers DESC
;

-- Find the total customers by gender
SELECT
  gender,
  COUNT(customer_key) AS total_customers
FROM
  dim_customers
GROUP BY
  gender
ORDER BY
  total_customers DESC
;

-- Find total products by category
SELECT
  category,
  COUNT(product_key) AS total_products
FROM
  dim_products
GROUP BY
  category
ORDER BY
  total_products DESC
;

-- What is the average costs in each category?
SELECT
  category,
  ROUND(AVG(cost), 2) AS avg_cost
FROM
  dim_products
GROUP BY
  category
ORDER BY
  avg_cost DESC
;

-- What is the total revenue generated for each category?
SELECT
  p.category,
  SUM(f.sales_amount) AS total_revenue
FROM
  fact_sales AS f
LEFT JOIN dim_products AS p
  ON f.product_key = p.product_key
GROUP BY
  p.category
ORDER BY
  total_revenue DESC
;

-- What is the total revenue generated by top 50 customer?
SELECT
  c.customer_key,
  c.first_name,
  c.last_name,
  SUM(f.sales_amount) AS total_revenue
FROM
  fact_sales AS f
LEFT JOIN dim_customers AS c
  ON f.customer_key = c.customer_key
GROUP BY
  c.customer_key,
  c.first_name,
  c.last_name
ORDER BY
  total_revenue DESC
LIMIT 50
;

-- What is the distribution of items sold across countries?
 SELECT
  c.country,
  SUM(f.quantity) AS total_sold_items
FROM
  fact_sales AS f
LEFT JOIN dim_customers AS c
  ON f.customer_key = c.customer_key
GROUP BY
  c.country
ORDER BY
  total_sold_items DESC
;


-- 5. Ranking Analysis (Top & Bottom Performers)

-- Which 5 Products generate the highest revenue?
SELECT
  p.product_name,
  SUM(f.sales_amount) AS total_revenue,
  ROW_NUMBER() OVER(ORDER BY SUM(f.sales_amount) DESC) AS rank_products
FROM
  fact_sales AS f
LEFT JOIN dim_products AS p
  ON f.product_key = p.product_key
GROUP BY
  p.product_name
LIMIT 5
;

-- What are the 5 worst-performing products in terms of sales?
SELECT
  p.product_name,
  SUM(f.sales_amount) AS total_revenue,
  ROW_NUMBER() OVER(ORDER BY SUM(f.sales_amount) ASC) AS rank_products
FROM
  fact_sales AS f
LEFT JOIN dim_products AS p
  ON f.product_key = p.product_key
GROUP BY
  p.product_name
LIMIT 5
;

-- Find the Top-10 customers who have generated the highest revenue?  
SELECT
  c.customer_key,
  c.first_name,
  c.last_name,
  SUM(f.sales_amount) AS total_revenue,
  ROW_NUMBER() OVER(ORDER BY SUM(f.sales_amount) DESC) AS rank_customers
FROM
  fact_sales AS f
LEFT JOIN dim_customers AS c
  ON f.customer_key = c.customer_key
GROUP BY
  c.customer_key,
  c.first_name,
  c.last_name
LIMIT 10
;

-- Find the 3 customers with the fewest orders placed?
SELECT
  c.customer_key,
  c.first_name,
  c.last_name,
  COUNT(f.order_number) AS total_orders,
  ROW_NUMBER() OVER(ORDER BY SUM(f.sales_amount) ASC) AS rank_customers
FROM
  fact_sales AS f
LEFT JOIN dim_customers AS c
  ON f.customer_key = c.customer_key
GROUP BY
  c.customer_key,
  c.first_name,
  c.last_name
LIMIT 3
;

